### ISSUE TITLE
Handle Slicing of NNModuleList

### ISSUE THREAD

**Issue by anijain2305** [facebookresearch/torchdynamo#149]
Repro 
~~~
import torch
import torchdynamo


class ModuleList(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = torch.nn.ModuleList(
            [
                torch.nn.Linear(10, 10),
                torch.nn.ReLU(),
                torch.nn.Linear(10, 10),
                torch.nn.ReLU(),
            ]
        )

    def forward(self, x):
        x = self.layers[0](x) 
        x = self.layers[0:1:1][0](x)
        # for idx, layer in enumerate(self.layers[::-1]):
        #     x = layer(x) * idx

        return x


mod = ModuleList()
x = torch.randn(10, 10)
ref = mod(x)

with torchdynamo.optimize("eager", nopython=True):
    mod(x)
~~~

The tracing log is as follows

~~~
TRACE LOAD_ATTR layers [NNModuleVariable()]
TRACE LOAD_CONST 0 [NNModuleVariable()]
TRACE LOAD_CONST 1 [NNModuleVariable(), ConstantVariable(int)]
TRACE LOAD_CONST 1 [NNModuleVariable(), ConstantVariable(int), ConstantVariable(int)]
TRACE BUILD_SLICE 3 [NNModuleVariable(), ConstantVariable(int), ConstantVariable(int), ConstantVariable(int)]
TRACE BINARY_SUBSCR None [NNModuleVariable(), SliceVariable()]
TRACE LOAD_CONST 0 [UnspecializedNNModuleVariable(ModuleList)]
~~~

I am suspicious of the last line, where it creates an `UnspecializedNNModuleVariable`. The ModuleLists are getting tagged as dynamic probably here - https://github.com/facebookresearch/torchdynamo/blob/main/torchdynamo/mutation_guard.py#L88

The error right now is 

~~~
Traceback (most recent call last):
  File "/fsx/users/anijain/torchdynamo/torchdynamo/convert_frame.py", line 179, in _convert_frame_assert
    return GuardedCode(code, output.guards, frame.f_locals, frame.f_globals)
  File "/fsx/users/anijain/torchdynamo/torchdynamo/guards.py", line 309, in __init__
    self.check_fn = self.compile_check_fn(local_builder, global_builder)
  File "/fsx/users/anijain/torchdynamo/torchdynamo/guards.py", line 358, in compile_check_fn
    exec(py_code, global_builder.scope, out)
  File "<string>", line 3
    return lambda x,self,0,**___kwargs_ignored: ___guarded_code.valid and ___check_obj_id(self, 139827490789984) and self.training and ___check_type_id(self.layers[slice(0, 1, 1)]._modules, 94111194889184) and self.layers[slice(0, 1, 1)]._modules.keys() == {'0'} and ___check_obj_id(self.layers[slice(0, 1, 1)]._modules['0'], 139827490788928) and self.layers[slice(0, 1, 1)]._modules['0'].training and ___check_tensors(x)
                         ^
SyntaxError: invalid syntax
~~~

**Comment by jansel** [comment]
Yeah, seems like there are two bugs here.
1) it should be a NNModuleVariable not an UnspecializedNNModuleVariable
2) the guard logic shouldn't pass `0` as an arg

**Comment by anijain2305** [comment]
Fixed by https://github.com/facebookresearch/torchdynamo/pull/152
