### ISSUE TITLE
Debug python key tracing error with hf_Reformer

### ISSUE THREAD

**Issue by jansel** [facebookresearch/torchdynamo#81]
Repro
```
./torchbench.py --no-skip --python-key -n 1 -k hf_Reformer
```

Error:
```
Traceback (most recent call last):
  File "/home/jansel/torchdynamo/torchdynamo/output_graph.py", line 317, in call_user_compiler
    compiled_fn = self.compiler_fn(gm, self.example_inputs())
  File "/home/jansel/torchdynamo/torchdynamo/optimizations/python_key.py", line 137, in python_key
    gm, make_wrapper = python_key_normalize(gm, example_inputs)
  File "/home/jansel/torchdynamo/torchdynamo/optimizations/python_key.py", line 120, in python_key_normalize
    graph = tracer.trace(fake_signature(fn_for_tracing, nargs))
  File "/home/jansel/pytorch/torch/fx/_symbolic_trace.py", line 577, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "<string>", line 1, in <lambda>
  File "/home/jansel/torchdynamo/torchdynamo/optimizations/python_key.py", line 114, in fn_for_tracing
    out = PatchingInterpreter(gm).run(*args[params_len:])
  File "/home/jansel/pytorch/torch/fx/interpreter.py", line 120, in run
    self.env[node] = self.run_node(node)
  File "/home/jansel/torchdynamo/torchdynamo/optimizations/python_key.py", line 77, in run_node
    result = super().run_node(n)
  File "/home/jansel/pytorch/torch/fx/interpreter.py", line 147, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/jansel/pytorch/torch/fx/interpreter.py", line 241, in call_method
    return getattr(self_obj, target)(*args_tail, **kwargs)
RuntimeError: DispatchKey PythonTLSSnapshot doesn't correspond to a device
```

This is coming from a call to `Tensor.new` it seems.

cc @Chillee @anijain2305

**Comment by bitfort** [comment]
for 1.13: Try to fix the bug, if we can't easily fix, then silence the warning / error and come back to fix for another release.

**Comment by Chillee** [comment]
The error is fixed by this: https://github.com/pytorch/pytorch/pull/74971

I'm not actually quite sure where this error comes from, but experimentally this patch fixes it.

**Comment by jansel** [comment]
Thanks!  Yeah, seems like a tricky fix to find...

**Comment by Chillee** [comment]
haha, @ezyang just saw the error message and suggested this fix :P 

Some other folks were also running into this.

**Comment by Chillee** [comment]
Appears to be fixed on master.
