### ISSUE TITLE
Debug issue with AOTAutograd for speech_transformer/hf_GPT2/hf_T5

### ISSUE THREAD

**Issue by anijain2305** [facebookresearch/torchdynamo#85]
The three models - speech_transformer, hf_GPT2 and hf_T5 fail with similar type of error signature.

TorchDynamo finds static subgraphs and sends them to AOT Autograd. AOT Autograd generates the forward and backward graphs. The output of AOT Autograd is a autograd.Function ([code](https://github.com/pytorch/functorch/blob/main/functorch/_src/aot_autograd.py#L136-L178)). AOT Autograd saves some tensors for the backward pass gradient computation in the forward pass.

The issue arises in the backward pass. When we read the saved_tensors, one of the item in the `saved_tensors` is not of Tensor type anymore. This causes cryptic error messages like the one below. And this type changes from run to run. I have seen immutable_dict, tuple and even weakref and builtin. 

~~~
ERROR:root:unhandled error
Traceback (most recent call last):
  File "torchbench.py", line 1006, in run_one_model
    new_result = model_iter_fn(model, example_inputs)
  File "torchbench.py", line 482, in forward_and_backward_pass
    def forward_and_backward_pass(mod, inputs, collect_outputs=True):
  File "torchbench.py", line 482, in forward_and_backward_pass
    def forward_and_backward_pass(mod, inputs, collect_outputs=True):
  File "torchbench.py", line 482, in forward_and_backward_pass
    def forward_and_backward_pass(mod, inputs, collect_outputs=True):
  [Previous line repeated 2 more times]
  File "/fsx/users/anijain/functorch/functorch/_src/monkey_patching.py", line 97, in _backward
    return _old_backward(*args, **kwargs)
  File "/data/home/anijain/miniconda/envs/pytorch_dev/lib/python3.8/site-packages/torch/_tensor.py", line 395, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/data/home/anijain/miniconda/envs/pytorch_dev/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/data/home/anijain/miniconda/envs/pytorch_dev/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/fsx/users/anijain/torchdynamo/torchdynamo/eval_frame.py", line 58, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/anijain/functorch/functorch/_src/aot_autograd.py", line 188, in backward
    out = normalize_as_list(compiled_bw(*ctx.saved_tensors, *contiguous_args))
  File "/fsx/users/anijain/torchdynamo/torchdynamo/eval_frame.py", line 58, in _fn
    return fn(*args, **kwargs)
  File "/data/home/anijain/miniconda/envs/pytorch_dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: forward() Expected a value of type 'Tensor (inferred)' for argument 'primals_14' but instead found type 'tuple'.
Inferred 'primals_14' to be of type 'Tensor' because it was not annotated with an explicit type.
Position: 19
Value: ('___check_obj_id', '___check_tensors', '___check_type_id', '___guarded_code')

~~~

I further looked into C++ and starting printing the type of objects while saving the tensors at the end of forward pass, and reading them back in backward pass. I observed the weird behavior in this line -(https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/python_function.cpp#L834).  This is called in the backward pass, when we call ctx.saved_tensors.

When I print the unpacked_var, it is a *tensor*. It has its dim, I can print its shape and everything. 
But  Py_TYPE(value)→tp_name equals immutable_dict here. 
The unpack_fn is basically THPVariable_Wrap - (https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/python_function.cpp#L849).

For completeness, adding images for the failure

Repro - `python torchbench.py --training --devices=cuda --accuracy-aot-nop --only=hf_GPT2`
![image](https://user-images.githubusercontent.com/13822661/159565917-30b1735c-8a2d-4aec-8298-9d5df900e523.png)

Repro - `python torchbench.py --training --devices=cuda --accuracy-aot-nop --only=speech_transformer`
![image](https://user-images.githubusercontent.com/13822661/159565622-70e1680d-d934-470e-a1fd-bd4c2ff63568.png)

Repro - `python torchbench.py --training --devices=cuda --accuracy-aot-nop --only=hf_T5`
![image](https://user-images.githubusercontent.com/13822661/159566100-50dea8e0-1a80-4d21-a2c6-b3aed8ecddc3.png)

**Comment by anijain2305** [comment]
Repro for the bug

~~~
import torch
from torch.nn import *
from functorch.compile import aot_module_simplified, nop
import torchdynamo
from torchdynamo.optimizations.training import aot_autograd_debug_strategy1
from torchdynamo.eval_frame import skip_code

class Bar(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.self_ln_1_weight = torch.nn.Parameter(torch.empty([768], dtype=torch.float32))
        self.self_ln_1_bias = torch.nn.Parameter(torch.empty([768], dtype=torch.float32))
        self.register_buffer('self_attn_bias', torch.empty([1, 1, 1024, 1024], dtype=torch.uint8))
        self.register_buffer('self_attn_masked_bias', torch.empty([], dtype=torch.float32))
        self.self_attn_c_attn_bias = torch.nn.Parameter(torch.empty([2304], dtype=torch.float32))
        self.self_attn_c_attn_weight = torch.nn.Parameter(torch.empty([768, 2304], dtype=torch.float32))

    def forward(self, hidden_states):
        self_ln_1_weight = self.self_ln_1_weight
        self_ln_1_bias = self.self_ln_1_bias
        layer_norm = torch.nn.functional.layer_norm(hidden_states, (768,), weight = self_ln_1_weight, bias = self_ln_1_bias, eps = 1e-05)
        self_attn_c_attn_bias = self.self_attn_c_attn_bias
        view = layer_norm.view(-1, 768)
        self_attn_c_attn_weight = self.self_attn_c_attn_weight
        addmm = torch.addmm(self_attn_c_attn_bias, view, self_attn_c_attn_weight)
        view_1 = addmm.view(4, 512, 2304)
        split = torch.functional.split(view_1, 768, dim = 2)
        getitem = split[0]
        getitem_1 = split[1]
        getitem_2 = split[2]
        view_2 = getitem.view(4, 512, 12, 64)
        permute = view_2.permute(0, 2, 1, 3)
        view_3 = getitem_1.view(4, 512, 12, 64)
        permute_1 = view_3.permute(0, 2, 1, 3)
        view_4 = getitem_2.view(4, 512, 12, 64)
        permute_2 = view_4.permute(0, 2, 1, 3)
        transpose = torch.transpose(permute_1, -1, -2)
        matmul = torch.matmul(permute, transpose)
        truediv = matmul / 8.0
        self_attn_bias = self.self_attn_bias
        getitem_3 = self_attn_bias[(slice(None, None, None), slice(None, None, None), slice(0, 512, None), slice(None, 512, None))]
        bool_1 = getitem_3.bool()
        self_attn_masked_bias = self.self_attn_masked_bias
        to = self_attn_masked_bias.to(torch.float32)
        where = torch.where(bool_1, truediv, to)
        softmax = torch.nn.functional.softmax(where, -1)
        type_1 = softmax.type(torch.float32)
        dropout = torch.nn.functional.dropout(type_1, p = 0.1, training = False)
        matmul_1 = torch.matmul(dropout, permute_2)
        permute_3 = matmul_1.permute(0, 2, 1, 3)
        contiguous = permute_3.contiguous()
        view_5 = contiguous.view((4, 512, 768))
        return (view_5, )

modules = []
aot_modules = []
num_hidden_layers = 12
for idx in range(num_hidden_layers):
    mod = Bar().to(device="cuda")
    modules.append(mod)
    aot_modules.append(aot_module_simplified(mod, nop))

class MockModule(torch.nn.Module):
    def __init__(self, use_aot):
        super().__init__()
        self.embed_dim = 768
        self.use_aot = use_aot
    
    def forward(self, x):
        hidden_states = x
        for idx in range(num_hidden_layers):
            if self.use_aot:
                outputs = aot_modules[idx](hidden_states)
            else:
                outputs = modules[idx](hidden_states)
            hidden_states = outputs[0]
        return hidden_states


x = torch.randn(torch.Size([4, 512, 768]), device="cuda", requires_grad=True)

# Torch baseline
mod = MockModule(use_aot=False).to("cuda")
ref = mod(x)
ref[0].sum().backward()

# AOT - no Dynamo
# aot_mod = MockModule(use_aot=True).to("cuda")
# res = aot_mod(x)
# res[0].sum().backward()

# Dynamo with AOT
with torchdynamo.optimize(aot_autograd_debug_strategy1):
    # Use aot should be false. Backend is already set to be AOT
    aot_mod = MockModule(use_aot=False).to("cuda")
    skip_code(aot_mod.forward.__code__)
    res = aot_mod(x)
    res[0].sum().backward()

print("Success")
~~~

**Comment by anijain2305** [comment]
@Chillee has been looking at this and isolated the problem with even smaller repro than the above. Assigning this to him.

**Comment by Chillee** [comment]
Resolved in https://github.com/pytorch/pytorch/pull/75933
